/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Authentification (void);
GtkWidget* create_Gestion_utilisateur (void);
GtkWidget* create_Gestion_des_elections (void);
GtkWidget* create_Gestion_Observateur (void);
GtkWidget* create_Espace_Admin (void);
GtkWidget* create_Espace_Electeur (void);
GtkWidget* create_gestion_liste_electorale (void);
GtkWidget* create_windowvote (void);
GtkWidget* create_Statistique2 (void);
GtkWidget* create_GESTION_DE_BV (void);
GtkWidget* create_Statistique1 (void);
