/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Authentification;
  GtkWidget *Gestion_utilisateur;
  GtkWidget *Gestion_des___lections;
  GtkWidget *Gestion_Observateur;
  GtkWidget *Espace_Admin;
  GtkWidget *Espace_Electeur;
  GtkWidget *gestion_liste_electorale;
  GtkWidget *windowvote;
  GtkWidget *Statistique2;
  GtkWidget *GESTION_DE_BV;
  GtkWidget *Statistique1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ( "../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Authentification = create_Authentification ();
  gtk_widget_show (Authentification);
  /*Gestion_utilisateur = create_Gestion_utilisateur ();
  gtk_widget_show (Gestion_utilisateur);
  Gestion_des___lections = create_Gestion_des___lections ();
  gtk_widget_show (Gestion_des___lections);
  Gestion_Observateur = create_Gestion_Observateur ();
  gtk_widget_show (Gestion_Observateur);
  Espace_Admin = create_Espace_Admin ();
  gtk_widget_show (Espace_Admin);
  Espace_Electeur = create_Espace_Electeur ();
  gtk_widget_show (Espace_Electeur);
  gestion_liste_electorale = create_gestion_liste_electorale ();
  gtk_widget_show (gestion_liste_electorale);
  windowvote = create_windowvote ();
  gtk_widget_show (windowvote);
  Statistique2 = create_Statistique2 ();
  gtk_widget_show (Statistique2);
  GESTION_DE_BV = create_GESTION_DE_BV ();
  gtk_widget_show (GESTION_DE_BV);
  Statistique1 = create_Statistique1 ();
  gtk_widget_show (Statistique1);*/

  gtk_main ();
  return 0;
}

